# Generated by Django 4.2.5 on 2023-10-03 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-id'], 'verbose_name': 'Contact Form', 'verbose_name_plural': 'Contact Forms'},
        ),
        migrations.AddField(
            model_name='contactform',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
